spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
